async(page)=>{
 const trace=[],errors=[];page.on('pageerror',e=>errors.push(String(e)));
 const state=()=>page.evaluate(()=>{const e=blackSun.expedition,w=e.world,p=w.player;return {state:e.state,mode:blackSun.mode,zone:e.zoneId,t:e.seconds,hp:p.hp,x:p.x,y:p.y,vy:p.vy,ground:p.grounded,width:w.width,height:w.height,activity:e.activity,medkits:e.medkits,cargo:{...e.cargo},rig:e.rig.modules.map(m=>m.kind),combos:e.rig.combos,escort:e.discovery.escort,shortcuts:[...e.profile.shortcuts],residents:e.profile.residents,last:e.lastRecord,cam:{x:blackSun.cameras.main.scrollX,y:blackSun.cameras.main.scrollY},portals:e.portals,platforms:w.platforms,enemies:w.enemies.filter(n=>!n.dead).map(n=>({x:n.x,y:n.y,hp:n.hp,kind:n.kind})),modules:w.modules.filter(m=>!m.dead&&!m.parent&&!m.mounted).map(m=>({x:m.x,y:m.y,kind:m.kind})),loot:e.state==='field'?e.area.loot.filter(l=>!l.taken):[],features:e.discovery.features.filter(f=>f.zoneId===e.zoneId&&!f.done)};});
 const box=await page.locator('canvas').boundingBox();const aim=async(x,y,s)=>page.mouse.move(box.x+Math.max(5,Math.min(1275,x-s.cam.x))*box.width/1280,box.y+Math.max(5,Math.min(715,y-s.cam.y))*box.height/720);
 const release=async()=>{for(const k of ['a','d','Space','w','s'])await page.keyboard.up(k);await page.mouse.up();};
 const support=async(s)=>{if(s.state!=='field')throw Error('run ended');if(s.hp<65&&s.medkits)await page.keyboard.press('h');const enemy=s.enemies.filter(n=>Math.hypot(n.x-s.x,n.y-s.y)<780).sort((a,b)=>Math.hypot(a.x-s.x,a.y-s.y)-Math.hypot(b.x-s.x,b.y-s.y))[0];if(enemy){await aim(enemy.x,enemy.y,s);await page.mouse.down();}else await page.mouse.up();};
 const walk=async(x)=>{let oldX=-999,stuck=0;for(let i=0;i<900;i++){const s=await state();await support(s);if(Math.abs(s.x-x)<16){await page.keyboard.up('a');await page.keyboard.up('d');return;}stuck=Math.abs(s.x-oldX)<2?stuck+1:0;oldX=s.x;if(stuck>3&&s.ground){await page.keyboard.press('Space',{delay:190});stuck=0;}await page.keyboard.up(s.x<x?'a':'d');await page.keyboard.down(s.x<x?'d':'a');await page.waitForTimeout(80);}throw Error('walk blocked '+x);};
 const fight=async()=>{await page.keyboard.up('a');await page.keyboard.up('d');for(let i=0;i<140;i++){const s=await state();await support(s);if(!s.enemies.some(n=>Math.hypot(n.x-s.x,n.y-s.y)<780))break;await page.waitForTimeout(90);}await page.mouse.up();};
 const connect=async()=>{for(let n=0;n<4;n++){let s=await state();const m=s.modules.filter(m=>!s.rig.includes(m.kind)&&Math.abs(m.x-s.x)<600).sort((a,b)=>Math.abs(a.x-s.x)-Math.abs(b.x-s.x))[0];if(!m||s.rig.length>=3)break;await walk(m.x);await page.waitForTimeout(250);await page.keyboard.press('e',{delay:70});await page.waitForTimeout(120);}trace.push({event:'rig',...await state()});};
 const jumpTo=async(p)=>{await page.keyboard.up('Space');await page.waitForTimeout(100);await page.keyboard.down('Space');for(let i=0;i<75;i++){const s=await state();await support(s);const dx=p.x-s.x;await page.keyboard.up(dx>0?'a':'d');if(Math.abs(dx)>10)await page.keyboard.down(dx>0?'d':'a');else{await page.keyboard.up('a');await page.keyboard.up('d');}if(i>4&&s.ground&&Math.abs(s.y-(p.y-p.h/2-24))<18){await page.keyboard.up('Space');await page.keyboard.up('a');await page.keyboard.up('d');return;}await page.waitForTimeout(40);}throw Error('landing '+p.y);};
 const climb=async()=>{const s=await state(),tiers=Math.floor((s.height-620)/95),stairs=s.platforms.slice(1,tiers+1);await walk(stairs[0].x-140);await page.waitForTimeout(650);for(const p of stairs){const a=await state();if(a.y<p.y-20)continue;await jumpTo(p);}trace.push({event:'climbed',...await state()});};
 const gate=async(to)=>{let s=await state(),p=s.portals.find(p=>p.to===to&&!p.ability);if(!p)throw Error('missing portal '+to);if(p.y<s.height-600&&s.y>p.y+100)await climb();if(p.y>=s.height-160&&s.y<p.y-150){await page.keyboard.down('s');await page.waitForFunction(()=>blackSun.expedition.world.player.y>blackSun.expedition.world.height-150);await page.keyboard.up('s');}await walk(p.x);await page.waitForTimeout(200);await page.waitForFunction(()=>blackSun.expedition.travelCooldown<=0);await page.keyboard.press('w',{delay:90});await page.waitForTimeout(150);s=await state();if(s.zone!==to)throw Error('gate failed '+to+' from '+s.zone);trace.push({event:'travel '+to,t:s.t,hp:s.hp,activity:s.activity,rig:s.rig,cargo:s.cargo});};
 const search=async(id)=>{let s=await state();const f=[...s.loot,...s.features].find(n=>n.id===id);if(!f)throw Error('missing search '+id);await walk(f.x);await fight();await page.mouse.up();await page.keyboard.down('w');await page.waitForTimeout(3300);await page.keyboard.up('w');trace.push({event:id,...await state()});};
 const finish=async()=>{await release();await page.keyboard.press('Escape');return{trace,final:await state(),errors};};

 try{await page.locator('[data-action=depart]').click();await page.waitForFunction(()=>document.getElementById('overlay').hidden);await search('airlock-0');await gate('concourse');await walk(1100);await fight();await connect();await search('concourse-0');await gate('turbine');await fight();await connect();await gate('core');await fight();await connect();await gate('pipes');await gate('nursery');await search('nursery-0');await gate('quarantine');await search('quarantine-2');await gate('station');await walk(3200);await fight();await page.keyboard.down('w');await page.waitForTimeout(5200);await page.keyboard.up('w');await gate('market');await search('market-0');await search('market-1');await gate('tower');await search('tower-0');await walk(3200);await fight();await page.keyboard.down('w');await page.waitForTimeout(6500);await page.keyboard.up('w');await gate('crown');
 await walk(310);for(const platform of (await state()).platforms.slice(1,5))await jumpTo(platform);let high=await state();await jumpTo(high.platforms.find(q=>q.x===1300&&q.y===high.height-460));await walk(1450);high=await state();await jumpTo(high.platforms.find(q=>q.x===1730&&q.y===high.height-460));await search('dawn-lens');
 const decision=await state();trace.push({event:'lens taken',...decision});await page.screenshot({path:'output/playwright/v4-tower-lens.png'});await gate('tower');await page.keyboard.down('s');await page.waitForFunction(()=>blackSun.expedition.world.player.y>blackSun.expedition.world.height-150);await page.keyboard.up('s');let s=await state();if(s.shortcuts.includes('S3')){const lift=s.portals.find(p=>p.id==='S3');await walk(lift.x);await page.keyboard.press('w',{delay:90});await page.waitForTimeout(180);await gate('quarantine');await gate('station');}else await gate('station');
 await walk(3200);await page.keyboard.press('w',{delay:90});await page.waitForTimeout(170);await gate('airlock');await walk(175);await page.keyboard.down('w');await page.waitForTimeout(1800);await page.keyboard.up('w');const final=await state();return{passed:final.state==='hub',decision,trace,final,errors};}
 catch(error){await release();const final=await state();if(final.state==='field'&&!final.mode)await page.keyboard.press('Escape');return{error:String(error),trace,final,errors};}
}